### ISSUE TITLE
Copy to clipboard

### ISSUE THREAD

**Issue by Nico207** [zint/zint#20]
Hi,

can you add a "Copy to clipboard" function? (button or shortcut)

Thanks.

**Comment by Finkregh** [comment]
:+1:

**Comment by xelan** [comment]
I don't have a lot of experience with Qt4, but shouldn't it be enough to use the existing save method (`m_bc.bc.save_to_file()`) with a temporary file and copy to the clipboard from there?

```
// from https://stackoverflow.com/questions/14360201/qclipboard-send-image-to-system-clipboard
QImage image("clipboard_temp.png");
Q_ASSERT(!image.isNull());
QApplication::clipboard()->setImage(image, QClipboard::Clipboard);
```

See [mainwindow.cpp](https://github.com/zint/zint/blob/master/frontend_qt4/mainwindow.cpp#L145)

Thank you very much!

**Comment by Nico207** [comment]
Request was done in the real repository (at sourceforge) : 
https://sourceforge.net/p/zint/tickets/37/

> _mikemaikaefer say :_ 
> **This  is not the original ZINT repository** but an outdated fork only.
> Please refer to the original ZINT project at sourceforge.net!
