### ISSUE TITLE
Multiple Definition: backend source file code16k.c and code128.c multiple definition of `list'

### ISSUE THREAD

**Issue by uikino** [zint/zint#78]
# Bug
The variable `list` multiple definition in code16k.c line 44 ,code128.c line 42
# Solution
Precede `list` variables with the `static` keyword
like that
```
// code16k.c line 44
static int list[2][170];
```
```
// code128.c line 42
static int list[2][170];
```
Sorry,my English is poor

**Comment by kingbuzzman** [comment]
I have the same issue.. any update on this?

**Comment by kingbuzzman** [comment]
After struggling with this, and even creating a [stackoverflow question](https://stackoverflow.com/questions/70710584/zint-not-compiling-in-newer-versions-of-debian) to assist my search. It boiled down to just using the more [up to date/official repo over at sourceforge](https://sourceforge.net/p/zint/code/ci/master/tree/) if you need the code, or just use the [artifacts of a particular release](https://sourceforge.net/projects/zint/files/zint/) you're interested in (which is what i used).

**Comment by uikino** [comment]
@kingbuzzman I'm so sorry for forgetting about these issues while on vacation for Chinese New Year.I actually raised this issue while waiting for the author to fix it, but I forgot that the issue was still open because I was busy at work. thank you.

**Comment by uikino** [comment]
# Solution
## please goto [official repo at sourceforge](https://sourceforge.net/p/zint/code/ci/master/tree/)
